name: PRB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sailpoint-cli-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
          
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: make install
        
      - name: Init connector project
        run: sail conn init connTest
        
      - name: Build and package connector zip file
        working-directory: ./connTest
        run: |
          npm install
          npm run pack-zip
